### ISSUE TITLE
RoboFlow v3.4.0 preview 8 does not start

### ISSUE THREAD

**Issue by 3110** [elephantrobotics/RoboFlow#1]
**Describe the bug**
When I start RoboFlow v3.4.0 preview 8, the error dialog "Cannot find/connect to the Robot" pops up (see the screenshot section). In the same environment, RoboFlow v3.4.0 preview 7 can start normally.

**To Reproduce**
1. Dobule-click on RoboFlow.exe

**Expected behavior**
RoboFlow will start normally.

**Screenshots**
![59b9b6414eda60d2e2332ba002adb1b0](https://user-images.githubusercontent.com/114928/129207737-c4e7b636-ac70-454f-9002-a40bf611b4e9.png)

**Environment:**
 - RoboFlow version: 3.4.0 preview 8
 - OS: Windows 11
 - Robot: myCobot 280 (M5 version)

**Comment by fedorenchik** [comment]
Please, can you check what are Atom's and M5 Basic's apps and versions ?

**Comment by 3110** [comment]
Atom
* AtomMain v3.2

Basic
* minirobot v0.4

**Comment by lxw119** [comment]
Hello,can you upload the picture of preview 8 login page?And do you have system of win10,if you have can you check on it?

**Comment by 3110** [comment]
@lxw119 Before the login page appears, the error dialog pops up.  I'm sorry that I don't have Windows 10 environment right now.

**Comment by fedorenchik** [comment]
@3110  Looks like one of previous RoboFlow versions. In preview 8 we removed this check and always show login page first. I've tried in Windows 11 and it can work.

Can you re-download preview 8 and try again ?

https://www.elephantrobotics.com/en/downloads/

Also, make sure m5 basic driver CP210x is installed:

https://docs.m5stack.com/en/download

**Comment by 3110** [comment]
@fedorenchik Thank you. I can see the login page with the re-download preview 8, but I can't log in as Admin.  According to https://github.com/elephantrobotics/RoboFlow/issues/2, Admin can automatically login with no password from preview 7. Pushing the "Start" button with an empty password shows a "Wrong password" message in the password field.

![キャプチャ](https://user-images.githubusercontent.com/114928/130024227-12ecdd78-8d3d-4ee8-9b79-a240cc571364.PNG)

P.S.
I can automatically log in as Admin with preview 7.

**Comment by fedorenchik** [comment]
Please, try password "mycobot". Since preview 8 default password is "mycobot".

**Comment by 3110** [comment]
@fedorenchik OK. Is the automatic login disabled in preview 8?

**Comment by fedorenchik** [comment]
@3110  Yes, automatic login is disabled.

**Comment by 3110** [comment]
@fedorenchik OK, thank you.
