### ISSUE TITLE
Failed to log in as Admin with the correct password

### ISSUE THREAD

**Issue by 3110** [elephantrobotics/RoboFlow#2]
**Describe the bug**
I can't log in as Admin with the correct password. The "Wrong password" message shows in the password field. 
If I exit RoboFlow after failing to log in with the correct password and start it again, I can log in as Admin automatically.

**To Reproduce**
1. Run RoboFlow
2. Set user to Admin
3. Input Admin password
4. Push "Start" button  
-> "Wrong password" shows in the password field
5. Exit RoboFlow
6. Run RoboFlow again  
-> Automatically log in as Admin

**Expected behavior**
I can log in as Admin in Step 4 

**Environment:**
 - RoboFlow version: v3.4.0 preview 7
 - OS: Windows 11
 - Robot: myCobot 280 (M5 version)    
   - Atom: AtomMain v3.2
   - Basic: minirobot v0.4

**Comment by Eheech** [comment]
i wanna confirm, have you saved your password ? our tester have followed your reproduce steps but don't have this problem ... and it would be very grateful for us if you can try this function again .... if this problem happened again, please tell us .. Thank you very much.

**Comment by 3110** [comment]
@Eheech No, I don't have saved the password (using the default password "aaa").  I can reproduce the error from the first time I install RoboFlow and start it.

**Comment by Eheech** [comment]
but preview7 don't have to input password, preview6 using default password "aaa" ...

**Comment by 3110** [comment]
OK, I don't have known the spec change in preview 7.  Thanks.
