### ISSUE TITLE
FreeMove locks all joints

### ISSUE THREAD

**Issue by 3110** [elephantrobotics/RoboFlow#3]
**Describe the bug**
When I push any "FreeMove" button, all joints are locked. 

**To Reproduce**

The same steps in https://youtu.be/9scJlqW7mfQ

1. Run RoboFlow
2. Log in as Admin
3. Select "Program Robot" in Main Menu
4. Select "Empty Program" in "Create a program"
5. Push "FreeMove" button

**Expected behavior**
After the steps above, I can move all joints freely.

**Environment (please complete the following information):**
 - RoboFlow version: 3.4.0 preview 8 (re-download version)
 - M5 Atom firmware and version: AtomMain 3.2
 - M5 Basic firmware and version: minirobot 0.4
 - OS: Windows 11
 - Robot: myCobot 280 (M5Stack version)

**Comment by Eheech** [comment]
I would like to ask, after you pushed "FreeMove" button, did Atom's color change ?

**Comment by 3110** [comment]
@Eheech Yes, it turns yellow from green.

**Comment by Eheech** [comment]
Have you pressed Atom? FreeMove need to press Atom when you want to move all joints, and when you release Atom, all joints will be locked.

**Comment by 3110** [comment]
@Eheech Oh, I know! Thank you.

**Comment by 3110** [comment]
@Eheech How can I turn off the free move mode?

1. Push the FreeMove button again
2. System Message dialog pops up (Please make sure the robot is stopped before turn off free mode. Are you sure to turn off free move?)
3. Push the Ok button

Nothing occurs, and stay in the free move mode.

**Comment by Eheech** [comment]
have the Atom color changed?

**Comment by Eheech** [comment]
when the Atom's color is yellow, it means FreeMove mode, when the Atom's color turn to green, it means FreeMove Close.

**Comment by Eheech** [comment]
And i wanna confirm, after you touched the OK button, have the FreeMove button turn to normal ? In FreeMove mode, FreeMove button is red (different from Home button and Original button).

**Comment by 3110** [comment]
@Eheech The Atom color remains yellow, and the FreeMove button remains highlighted (See attachment. In the quick move mode the button turns red).

![キャプチャ3](https://user-images.githubusercontent.com/114928/130648146-5b8d06fa-052b-46e2-9b3e-35fb751b3b6e.PNG)

After updating MyStudio from v3.1.0 to v3.1.1 and burning minirobot v0.0.4 again, this issue doesn't occur. So I close this issue. Thank you.
