### ISSUE TITLE
MyCobot Pi 280 - joints communication error

### ISSUE THREAD

**Issue by koleckit** [elephantrobotics/RoboFlow#4]
Hi! Anybody have similar problem?![image](https://user-images.githubusercontent.com/56119713/132259472-266608df-1562-4620-9841-f8872abd7171.jpeg)

**Comment by Eheech** [comment]
what's your Roboflow version ?

**Comment by Eheech** [comment]
Hope you problem is fixed, we will close your issue for now, if you meet this problem again, you can reopen it .

**Comment by kolboss** [comment]
Hi,

i have the same error, did anybody solve this problem?
